#!/bin/sh
#/etc/init.d/room-sensors

### BEGIN INIT INFO
# Provides:          room-sensors
# Required-Start:    $all mysql
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: initscript
# Description:       This service is used to manage websocket server
### END INIT INFO

export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/pi/room-sensors'
prog="/home/pi/room-sensors/websocket_server.py"

start() {
	echo -n "Starting $prog:"
	/usr/bin/python $prog > /dev/null & 
	echo
}


case "$1" in
	start)
		start
		;;
	*)
esac
