#!/bin/sh
# /etc/init.d/room-sensors

### BEGIN INIT INFO
# Provides:          room-sensors
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: initscript
# Description:       This service is used to manage websocket server
### END INIT INFO

RETVAL=0
export PATH='/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/sdelcore/bin'
prog="websocket_server.py"

start() {
	echo -n "Starting $prog:"
	$prog > /dev/null &
	echo
}

stop() {
	echo -n $"Stopping $prog:"
	killall room-sensors
	echo
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|status}"
esac
