#!/bin/sh
# /etc/init.d/room-sensors

### BEGIN INIT INFO
# Provides:          room-sensors
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: initscript
# Description:       This service is used to manage websocket server
### END INIT INFO

RETVAL=0
export PATH="$PATH:$proj_dir"
prog="websocket_server.py"

start() {
	echo -n $"Starting $prog:"
	RETVAL=$?
	[ "$RETVAL" = 0 ] && $prog > /dev/null &
	echo
}

stop() {
	echo -n $"Stopping $prog:"
	killproc $prog -TERM
	RETVAL=$?
	[ "$RETVAL" = 0 ] && rm -f /var/lock/subsys/$prog
	echo
}

reload() {
	echo -n $"Reloading $prog:"
	killproc $prog -HUP
	RETVAL=$?
	echo
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	status)
		status $prog
		RETVAL=$?
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|status}"
		RETVAL=1
esac
exit $RETVAL
